In [2]:
import pandas as pd
import numpy as np
import bz2

In [2]:
original_airline_data = pd.DataFrame()

for Years in ('1987','1988','1989','1990','1991','2001'):
    file_path = '/Users/abhishekshenoy/Documents/OneDrive/abhishekshenoy/669/project/'
    file_type = '.csv.bz2'
    url = file_path + Years +file_type
    raw_data = pd.read_csv(url, encoding='latin1')
    sample1000 = raw_data.sample(3300,random_state = 42) 
    original_airline_data = pd.concat([original_airline_data,sample1000])

print('total row is ' + str(len(original_airline_data)))

original_airline_data.to_csv('/Users/abhishekshenoy/Document/OneDrive/abhishekshenoy/669/PRE2/ailine_original_data.csv')

total row is 19800

In [7]:
#read mergered data file
original_airline_data = pd.read_csv('/Users/abhishekshenoy/Documents/OneDrive/abhishekshenoy/669/PRE2/Combined_21000.csv')
original_airline_data.sample(5)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
2058,190669,1987,10,15,4,1506.0,1500,1635.0,1624,PI,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
6521,2971700,1988,7,29,5,2151.0,2147,2246.0,2244,AA,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
10494,1859573,1989,5,18,4,1915.0,1914,2055.0,2041,TW,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
10051,4067288,1989,10,30,1,1732.0,1715,1902.0,1850,HP,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
18419,5613765,2001,12,29,6,1617.0,1600,1855.0,1845,WN,...,3.0,20.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [8]:
#replace NA with Zero
original_airline_data.fillna(0,inplace=True)

In [9]:
#create delays 
original_airline_data.loc[(original_airline_data['ArrDelay'] > 0.0) | (original_airline_data['DepDelay'] > 0.0) ,'Delays'] = 'Y'
original_airline_data.loc[(original_airline_data['ArrDelay'] <= 0.0) & (original_airline_data['DepDelay'] <= 0.0) ,'Delays'] = 'N'
original_airline_data.loc[(original_airline_data['ArrDelay'] > 0.0) | (original_airline_data['DepDelay'] > 0.0) ,'DelaysN'] = 1
original_airline_data.loc[(original_airline_data['ArrDelay'] <= 0.0) & (original_airline_data['DepDelay'] <= 0.0) ,'DelaysN'] = 0
original_airline_data.sample(5)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Delays,DelaysN
5466,3913766,1988,10,12,3,829.0,830,1107.0,1106,UA,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,Y,1.0
13024,777326,1990,2,26,1,535.0,535,922.0,922,AA,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,N,0.0
20252,4031470,2001,8,27,1,830.0,835,1040.0,1055,MQ,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,N,0.0
12377,3020977,1990,7,20,5,1330.0,1330,1436.0,1438,CO,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,N,0.0
19290,5024619,2001,10,11,4,1528.0,1529,1836.0,1825,AA,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,Y,1.0

In [10]:
original_airline_data.columns

Index(['Unnamed: 0', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime',
       'CRSDepTime', 'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum',
       'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay',
       'Delays', 'DelaysN'],
      dtype='object')

In [ ]:
# drop unnecessary columns
# run this cell when deal with data from mergering
original_airline_data = original_airline_data.drop(['DepTime','ArrTime','ActualElapsedTime','TailNum','AirTime','ArrDelay','DepDelay','TaxiIn', 'TaxiOut','Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay','WeatherDelay', 'NASDelay', 'SecurityDelay','LateAircraftDelay','FlightNum'],axis = 1)
original_airline_data.sample(5)

In [11]:
# drop unnecessary columns
# run this cell when deal with data download from csv file
original_airline_data = original_airline_data.drop(['Unnamed: 0','DepTime','ArrTime','ActualElapsedTime','TailNum','AirTime','ArrDelay','DepDelay','TaxiIn', 'TaxiOut','Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay','WeatherDelay', 'NASDelay', 'SecurityDelay','LateAircraftDelay','FlightNum'],axis = 1)
original_airline_data.sample(5)

,Year,Month,DayofMonth,DayOfWeek,CRSDepTime,CRSArrTime,UniqueCarrier,CRSElapsedTime,Origin,Dest,Distance,Delays,DelaysN
1845,1987,12,10,4,2134,2310,EA,96,ATL,FLL,581.0,Y,1.0
20628,2001,1,8,1,700,725,WN,85,PHX,LAX,370.0,N,0.0
3401,1987,10,26,1,750,850,US,60,BUF,DCA,296.0,Y,1.0
16930,1991,7,17,3,2035,2125,AS,50,KTN,SIT,0.0,Y,1.0
20355,2001,7,14,6,945,1055,HP,70,LAS,SNA,226.0,Y,1.0

In [ ]:
#save clean data
#original_airline_data.to_csv('/Users/suimeng/Documents/OneDrive/MengSui/669/PRE2/Combined_21000_clean.csv')

In [3]:
#read clean data
original_airline_data = pd.read_csv('/Users/abhishekshenoy/Document/OneDrive/abhishekshenoy/669/PRE2/Combined_21000_clean.csv')

In [4]:
#check instance balance 
original_airline_data['Delays'].value_counts()

Y    13020
N     7980
Name: Delays, dtype: int64

In [5]:
# upsample N instance 
from sklearn.utils import resample

original_airline_data_majority = original_airline_data[original_airline_data.Delays=='Y']
original_airline_data_minority = original_airline_data[original_airline_data.Delays=='N']

original_airline_data_minority_upsampled = resample(original_airline_data_minority, 
                                                    replace=True,     # sample with replacement
                                                    n_samples=13020,    # to match majority class
                                                    random_state=42) # reproducible results

original_airline_data = pd.concat([original_airline_data_majority, 
                                            original_airline_data_minority_upsampled])

In [6]:
original_airline_data['Delays'].value_counts()

N    13020
Y    13020
Name: Delays, dtype: int64

In [7]:
corr_matrixs = original_airline_data.corr()
corr_matrixs['DelaysN'].abs().sort_values(ascending=False).iloc[1:]

Year              0.119211
Unnamed: 0        0.111367
CRSArrTime        0.071774
Distance          0.061795
CRSDepTime        0.061673
FlightNum         0.054956
CRSElapsedTime    0.050894
Month             0.020798
DayofMonth        0.015541
DayOfWeek         0.004122
Name: DelaysN, dtype: float64

In [26]:
original_airline_data.drop('Unnamed: 0',axis=1,inplace=True)

# Process categoty with OneHotEncode
## Pipeline for processing data

In [27]:
# transform catogry into numeric value
x = original_airline_data.drop(['Delays','DelaysN','Year','FlightNum'],axis=1)
y = original_airline_data['Delays']

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

cat_transformer = Pipeline(steps=[("onehot", OneHotEncoder(handle_unknown='ignore'))])
cat_attr = ['Month','DayofMonth','DayOfWeek','UniqueCarrier','Origin','Dest']
preprocessor = ColumnTransformer(transformers=[("cat", cat_transformer, cat_attr)])

# Machine Learn -- RF, DT, SVM, LR
## Training Model

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, KFold, cross_validate, cross_val_score
from sklearn.metrics import accuracy_score
import pickle


base_models = [("dt_clf", DecisionTreeClassifier(random_state=42)),
               ("rf_clf", RandomForestClassifier(n_estimators = 300,random_state=42)),
               ("svm_clf",svm.NuSVC(random_state=42,gamma='auto')),
               ('lr_clf', LogisticRegression(random_state=42))]

kfolds = 10
split = KFold(n_splits=kfolds, shuffle=True, random_state=42)

for name, model in base_models:
    # pack preprocessing of data and the model in a pipeline:
    model_steps = Pipeline(steps=[('preprocessor', preprocessor),
                                 ('model', model)])
    
    # get cross validation score for each model:
    cv_results = cross_val_score(model_steps, 
                                 x, y, 
                                 cv=split,
                                 scoring="accuracy",
                                 n_jobs=-1)
    # Save the model as a pickle in a file 
     
    
    # output:[]
    min_score = round(min(cv_results), 4)
    max_score = round(max(cv_results), 4)
    mean_score = round(np.mean(cv_results), 4)
    std_dev = round(np.std(cv_results), 4)
    print(f"{name} cross validation accuarcy score: {mean_score} +/- {std_dev} (std) min: {min_score}, max: {max_score}")

dt_clf cross validation accuarcy score: 0.769 +/- 0.0068 (std) min: 0.7588, max: 0.7834
rf_clf cross validation accuarcy score: 0.8196 +/- 0.0041 (std) min: 0.8137, max: 0.8283
svm_clf cross validation accuarcy score: 0.608 +/- 0.0075 (std) min: 0.5991, max: 0.6256
lr_clf cross validation accuarcy score: 0.5868 +/- 0.007 (std) min: 0.5772, max: 0.5979

## Training via Random Forest and Check Accuracy Details

In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, KFold, cross_validate, cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import joblib



x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.33, random_state = 21)

kfolds = 10
split = KFold(n_splits=kfolds, shuffle=True, random_state=42)

model_steps = Pipeline(steps=[('preprocessor', preprocessor),
                              ('model', RandomForestClassifier(n_estimators = 300,random_state=21))])


# get cross validation score for each model:
y_pred = model_steps.fit(x_train,y_train).predict(x_test)

joblib.dump(model_steps, 'rf_clf.pkl')
print('model saved')
print('\n')
matrix = confusion_matrix(y_test, y_pred)
print(matrix )
print('\n')
score = round(accuracy_score(y_test, y_pred),4)*100
print(f'Accuracy of ths model is {score}')
print('\n')
report = classification_report(y_test, y_pred)
print(report)

model saved


[[3295  989]
 [1019 3291]]


Accuracy of ths model is 76.63


              precision    recall  f1-score   support

           N       0.76      0.77      0.77      4284
           Y       0.77      0.76      0.77      4310

    accuracy                           0.77      8594
   macro avg       0.77      0.77      0.77      8594
weighted avg       0.77      0.77      0.77      8594

# prediction

## Random Forest

In [19]:
#load trained model
clf = joblib.load('rf_clf.pkl')

path = '/Users/abhishekshenoy/Documents/OneDrive/abhishekshenoy/669/PRE2/'
filename_to_pred = 'Unclassified flights.xlsx'
filename_done_pred = '2021prediction.xlsx'

# read prediction file
exam_data = pd.read_excel(path+filename_to_pred)

#select predictors 
attr = ['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'CRSDepTime', 'CRSArrTime',
        'UniqueCarrier', 'CRSElapsedTime', 'Origin', 'Dest','Distance']
exam_data_x = exam_data[attr]

#predeict 
exam_data_pred = clf.predict(exam_data_x)

#combine data
exam_data_x['Delays'] = exam_data_pred

#save prediction results
#exam_data_x.to_excel(path+filename_done_pred)

exam_data_x

<ipython-input-19-d8639ea0846b>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exam_data_x['Delays'] = exam_data_pred

,Year,Month,DayofMonth,DayOfWeek,CRSDepTime,CRSArrTime,UniqueCarrier,CRSElapsedTime,Origin,Dest,Distance,Delays
0,2021,3,1,5,845,1035,DL,230,ATL,PHX,1587,Y
1,2021,1,1,1,1515,1657,US,102,ATL,PIT,526,Y
2,2021,2,12,1,815,1029,UA,314,ATL,SFO,2139,N
3,2021,2,12,1,1810,1955,US,105,ATL,PIT,526,Y
4,2021,1,3,4,1030,1545,WN,195,LAS,MSY,1501,Y
5,2021,1,12,6,2205,550,AA,285,LAX,IAD,2288,Y
6,2021,1,16,3,1505,1658,DL,113,ATL,MIA,595,Y
7,2021,1,3,4,1425,1650,WN,145,HOU,MDW,937,Y
8,2021,2,22,3,1340,1550,US,130,PIT,MCO,834,Y
9,2021,2,4,6,730,923,US,113,CLT,MIA,650,Y
10,2021,2,10,5,1949,2050,AA,61,MCO,MIA,193,Y
11,2021,2,19,7,1045,1150,WN,65,BUF,BWI,281,Y

## Decision Tree

In [31]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import joblib



x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.33, random_state = 21)

model_steps = Pipeline(steps=[('preprocessor', preprocessor),
                              ('model',  DecisionTreeClassifier(random_state=42))])

# get cross validation score for each model:
y_pred = model_steps.fit(x_train,y_train).predict(x_test)

joblib.dump(model_steps, 'dt_clf.pkl')
print('model saved')
print('\n')
matrix = confusion_matrix(y_test, y_pred)
print(matrix )
print('\n')
score = round(accuracy_score(y_test, y_pred),4)*100
print(f'Accuracy of ths model is {score}')
print('\n')
report = classification_report(y_test, y_pred)
print(report)

model saved


[[3439  845]
 [1548 2762]]


Accuracy of ths model is 72.15


              precision    recall  f1-score   support

           N       0.69      0.80      0.74      4284
           Y       0.77      0.64      0.70      4310

    accuracy                           0.72      8594
   macro avg       0.73      0.72      0.72      8594
weighted avg       0.73      0.72      0.72      8594

In [33]:
#load trained model
clf = joblib.load('dt_clf.pkl')

path = '/Users/abhishekshenoy/Document/OneDrive/abhishekshenoy/669/PRE2/'
filename_to_pred = 'Unclassified flights.xlsx'
filename_done_pred = '2021prediction.xlsx'

# read prediction file
exam_data = pd.read_excel(path+filename_to_pred)

#select predictors 
attr = ['Month', 'DayofMonth', 'DayOfWeek', 'CRSDepTime', 'CRSArrTime',
        'UniqueCarrier', 'CRSElapsedTime', 'Origin', 'Dest','Distance']
exam_data_x = exam_data[attr]

#predeict 
exam_data_pred = clf.predict(exam_data_x)

#combine data
exam_data_x['Delays'] = exam_data_pred

#save prediction results
#exam_data_x.to_excel(path+filename_done_pred)

exam_data_x

,Month,DayofMonth,DayOfWeek,CRSDepTime,CRSArrTime,UniqueCarrier,CRSElapsedTime,Origin,Dest,Distance,Delays
0,3,1,5,845,1035,DL,230,ATL,PHX,1587,Y
1,1,1,1,1515,1657,US,102,ATL,PIT,526,N
2,2,12,1,815,1029,UA,314,ATL,SFO,2139,N
3,2,12,1,1810,1955,US,105,ATL,PIT,526,Y
4,1,3,4,1030,1545,WN,195,LAS,MSY,1501,Y
5,1,12,6,2205,550,AA,285,LAX,IAD,2288,Y
6,1,16,3,1505,1658,DL,113,ATL,MIA,595,N
7,1,3,4,1425,1650,WN,145,HOU,MDW,937,Y
8,2,22,3,1340,1550,US,130,PIT,MCO,834,Y
9,2,4,6,730,923,US,113,CLT,MIA,650,Y
10,2,10,5,1949,2050,AA,61,MCO,MIA,193,Y
11,2,19,7,1045,1150,WN,65,BUF,BWI,281,N

### Prediction svm

In [34]:
from sklearn import svm 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import joblib



x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.33, random_state = 21)

model_steps = Pipeline(steps=[('preprocessor', preprocessor),
                              ('model',  svm.NuSVC(random_state=42,gamma='auto'))])

# get cross validation score for each model:
y_pred = model_steps.fit(x_train,y_train).predict(x_test)

joblib.dump(model_steps, 'svm_clf.pkl')
print('model saved')
print('\n')
matrix = confusion_matrix(y_test, y_pred)
print(matrix )
print('\n')
score = round(accuracy_score(y_test, y_pred),4)*100
print(f'Accuracy of ths model is {score}')
print('\n')
report = classification_report(y_test, y_pred)
print(report)

#load trained model
clf = joblib.load('svm_clf.pkl')

path = '/Users/abhishekshenoy/Document/OneDrive/abhishekshenoy/669/PRE2/'
filename_to_pred = 'Unclassified flights.xlsx'
filename_done_pred = '2021prediction.xlsx'

# read prediction file
exam_data = pd.read_excel(path+filename_to_pred)

#select predictors 
attr = ['Month', 'DayofMonth', 'DayOfWeek', 'CRSDepTime', 'CRSArrTime',
        'UniqueCarrier', 'CRSElapsedTime', 'Origin', 'Dest','Distance']
exam_data_x = exam_data[attr]

#predeict 
exam_data_pred = clf.predict(exam_data_x)

#combine data
exam_data_x['Delays'] = exam_data_pred

#save prediction results
#exam_data_x.to_excel(path+filename_done_pred)

exam_data_x

model saved


[[2475 1809]
 [1747 2563]]


Accuracy of ths model is 58.620000000000005


              precision    recall  f1-score   support

           N       0.59      0.58      0.58      4284
           Y       0.59      0.59      0.59      4310

    accuracy                           0.59      8594
   macro avg       0.59      0.59      0.59      8594
weighted avg       0.59      0.59      0.59      8594

,Month,DayofMonth,DayOfWeek,CRSDepTime,CRSArrTime,UniqueCarrier,CRSElapsedTime,Origin,Dest,Distance,Delays
0,3,1,5,845,1035,DL,230,ATL,PHX,1587,Y
1,1,1,1,1515,1657,US,102,ATL,PIT,526,N
2,2,12,1,815,1029,UA,314,ATL,SFO,2139,N
3,2,12,1,1810,1955,US,105,ATL,PIT,526,N
4,1,3,4,1030,1545,WN,195,LAS,MSY,1501,Y
5,1,12,6,2205,550,AA,285,LAX,IAD,2288,Y
6,1,16,3,1505,1658,DL,113,ATL,MIA,595,N
7,1,3,4,1425,1650,WN,145,HOU,MDW,937,Y
8,2,22,3,1340,1550,US,130,PIT,MCO,834,N
9,2,4,6,730,923,US,113,CLT,MIA,650,N
10,2,10,5,1949,2050,AA,61,MCO,MIA,193,Y
11,2,19,7,1045,1150,WN,65,BUF,BWI,281,N

### Prediction Logistic Regression

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import joblib



x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.33, random_state = 21)

model_steps = Pipeline(steps=[('preprocessor', preprocessor),
                              ('model',  LogisticRegression(random_state=42))])

# get cross validation score for each model:
y_pred = model_steps.fit(x_train,y_train).predict(x_test)

joblib.dump(model_steps, 'lr_clf.pkl')
print('model saved')
print('\n')
matrix = confusion_matrix(y_test, y_pred)
print(matrix )
print('\n')
score = round(accuracy_score(y_test, y_pred),4)*100
print(f'Accuracy of ths model is {score}')
print('\n')
report = classification_report(y_test, y_pred)
print(report)

#load trained model
clf = joblib.load('lr_clf.pkl')

path = '/Users/abhishekshenoy/Document/OneDrive/abhishekshenoy/669/PRE2/'
filename_to_pred = 'Unclassified flights.xlsx'
filename_done_pred = '2021prediction.xlsx'

# read prediction file
exam_data = pd.read_excel(path+filename_to_pred)

#select predictors 
attr = ['Month', 'DayofMonth', 'DayOfWeek', 'CRSDepTime', 'CRSArrTime',
        'UniqueCarrier', 'CRSElapsedTime', 'Origin', 'Dest','Distance']
exam_data_x = exam_data[attr]

#predeict 
exam_data_pred = clf.predict(exam_data_x)

#combine data
exam_data_x['Delays'] = exam_data_pred

#save prediction results
#exam_data_x.to_excel(path+filename_done_pred)

exam_data_x

model saved


[[2458 1826]
 [1761 2549]]


Accuracy of ths model is 58.26


              precision    recall  f1-score   support

           N       0.58      0.57      0.58      4284
           Y       0.58      0.59      0.59      4310

    accuracy                           0.58      8594
   macro avg       0.58      0.58      0.58      8594
weighted avg       0.58      0.58      0.58      8594

,Month,DayofMonth,DayOfWeek,CRSDepTime,CRSArrTime,UniqueCarrier,CRSElapsedTime,Origin,Dest,Distance,Delays
0,3,1,5,845,1035,DL,230,ATL,PHX,1587,Y
1,1,1,1,1515,1657,US,102,ATL,PIT,526,N
2,2,12,1,815,1029,UA,314,ATL,SFO,2139,N
3,2,12,1,1810,1955,US,105,ATL,PIT,526,Y
4,1,3,4,1030,1545,WN,195,LAS,MSY,1501,N
5,1,12,6,2205,550,AA,285,LAX,IAD,2288,N
6,1,16,3,1505,1658,DL,113,ATL,MIA,595,Y
7,1,3,4,1425,1650,WN,145,HOU,MDW,937,N
8,2,22,3,1340,1550,US,130,PIT,MCO,834,Y
9,2,4,6,730,923,US,113,CLT,MIA,650,N
10,2,10,5,1949,2050,AA,61,MCO,MIA,193,Y
11,2,19,7,1045,1150,WN,65,BUF,BWI,281,Y

## extract train, validation, test file

In [39]:
from sklearn.model_selection import train_test_split
x_train_validation, x_test, y_train_validation, y_test = train_test_split(x,y,test_size = 0.333, random_state = 42)
x_train, x_validation, y_train, y_validation = train_test_split(x_train_validation,y_train_validation,test_size = 0.333, random_state = 42)

train_set = pd.concat([x_train,y_train],axis =1 )
validation_set = pd.concat([x_validation,y_validation],axis =1 )
test_set = pd.concat([x_test,y_test],axis =1 )

train_set.to_csv('/Users/abhishekshenoy/Documents/OneDrive/abhishekshenoy/669/PRE2/train_set.csv')
validation_set.to_csv('/Users/abhishekshenoy/Documents/OneDrive/abhishekshenoy/669/PRE2/validation_set.csv')
test_set.to_csv('/Users/abhishekshenoy/Documents/OneDrive/abhishekshenoy/669/PRE2/test_set.csv')